---
title: "MAR_Sim"
output: html_document
date: '2022-06-08'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(mice)
```

## MAR (Dependence on categorical variable)
```{r}
# Creates function that create a dataset with 50 observations for a MUTLIPLE linear regression model with a categorical variable.  
MAR.create.data <- function(beta = 1, sigma2 = 1, n = 50,
                        run = 1, beta2 = 10, categorical_var = "gender" , category_one = "M", category_zero = "F") {
  set.seed(seed = run)
  x <- rnorm(n)
  # p represents probability of being in some group (E.g. Male = 1 vs Female = 0)
  z <- rbinom(n, 1, p = 0.5)
  temp <- cbind(x = x, z = z)
  # Note the beta2 term for categorical variable effect.
  y <- beta * x + rnorm(n, sd = sqrt(sigma2)) + beta2 * z
  z[z == 0] <- category_zero
  z[z == 1] <- category_one
  # cat_var = categorical_var
  data <- cbind(x = x, y = y, categorical_var = z)
  # colnames(data) <- c("x", "y", categorical_var)
  # sort df by categorical variable.
  df <- as.data.frame(data) %>% 
    arrange(categorical_var)
}
# Creates function that removes p_0 % of data from category zero, p_1 % of data from category_one. Note this is effectively MCAR within each group (definition of MAR).
MAR.make.missing <- function(data, p_0 = 0.3, p_1 = 0.7 ){
  # don't generate nrow(data) times, generate count of category times.
  counts <- count(data, categorical_var)
  num_cat_zero <-counts[1,2]
  num_cat_one <- counts[2,2]
  r_zero <- rbinom(counts[1,2], 1, p_0)
  r_one <- rbinom(counts[2,2], 1, p_1)
  data[1:num_cat_zero,1][r_zero == 1] <- NA
  data[(num_cat_zero +1):nrow(data), 1][r_one ==1] <- NA
  data
}
# Function that calls mice (applying imputation) and applies Rubin's Rules, and creates 95% confidence intervals for parameter
MAR.test.impute <- function(data, m = 5, method = "norm", ... ,threshold =  1.0) {
  # Convert numerical vars to doubles (from character).
  data_num <- as.data.frame(apply(data[,c(1:2)], 2, as.numeric))
  # create copy
  data_num_complete <- data_num
  # add the categorical var
  data_num_complete$categorical_var <- data[,3]
  imp <- mice(data_num_complete, method = method, m = m, print = FALSE, ...)
  fit <- with(imp, lm(y ~ x + categorical_var))
  tab <- summary(pool(fit), "all", conf.int = TRUE)
  as.numeric(tab[2, c("estimate", "2.5 %", "97.5 %")])
}
```

```{r}
data <- MAR.create.data(n =50) %>% MAR.make.missing()
data %>% MAR.test.impute()

```


```{r}

# Must convert observation values to double from character in order for mice() to work. Add check # to MAR.test.impute() that converts first two columns (numerical vars) to double.
data <- MAR.create.data(n =50) %>% MAR.make.missing()
# Applying MAR.test.impute() manually for debugging purposes.
data_num <- as.data.frame(apply(data %>% select(x,y), 2, as.numeric))
data_num_complete <- data_num
data_num_complete$categorical_var <- (data$categorical_var)
imp <- mice(data_num_complete)
fit <- with(imp, lm(y ~ x))
tab <- summary(pool(fit), "all", conf.int = TRUE)
as.numeric(tab[2, c("estimate", "2.5 %", "97.5 %")])

# Gives us information regarding the logged event warning.
imp$loggedEvents

```



```{r}
simulate <- function(runs = 10) {
  res <- array(NA, dim = c(2, runs, 3))
  dimnames(res) <- list(c("norm.predict", "norm.nob"),
                        as.character(1:runs),
                        c("estimate", "2.5 %","97.5 %"))
  for(run in 1:runs) {
    data <- MAR.create.data(run = run)
    data <- MAR.make.missing(data)
    res[1, run, ] <- MAR.test.impute(data, method = "norm.predict",
                                 m = 2)
    res[2, run, ] <- MAR.test.impute(data, method = "norm.nob")
  }
  res
}
```

```{r}
# Run the simulation and store in res
res <- simulate(100)

```
```{r}
apply(res, c(1, 3), mean, na.rm = TRUE)

```
```{r}
true <- 1
RB <- rowMeans(res[,, "estimate"]) - true
PB <- 100 * abs((rowMeans(res[,, "estimate"]) - true)/ true)
CR <- rowMeans(res[,, "2.5 %"] < true & true < res[,, "97.5 %"])
AW <- rowMeans(res[,, "97.5 %"] - res[,, "2.5 %"])
RMSE <- sqrt(rowMeans((res[,, "estimate"] - true)^2))
data.frame(RB, PB, CR, AW, RMSE)
```

```{r}
head(imp$loggedEvents, 1)


```

## Analysis of response variable for observed X
```{r}
data <- MAR.create.data(n=50) %>% MAR.make.missing()
# data_imputed <- MAR.test.impute(data)

data_obs <- data[(complete.cases(data)), ]
# non-missing values
# cannot create histogram with type list, so must unlist and convert to numeric.
observed_y <- as.numeric(unlist(data_obs[2]))

hist(observed_y)
```
## Analysis of response variable for missing X

```{r}
# Missing Values
data_mis <- data[is.na(data),]
# cannot create histogram with type list, so must unlist and convert to numeric.
nonobserved_y <- as.numeric(unlist(data_mis[2]))

hist(nonobserved_y)

```



```{r}
simulate <- function(runs = 10) {
  res <- array(NA, dim = c(2, runs, 3))
  dimnames(res) <- list(c("norm.predict", "norm.nob"),
                        as.character(1:runs),
                        c("estimate", "2.5 %","97.5 %"))
  for(run in 1:runs) {
    data <- MAR.create.data(run = run)
    data <- MAR.make.missing(data)
    res[1, run, ] <- MAR.test.impute(data, method = "norm.predict",
                                 m = 2)
    res[2, run, ] <- MAR.test.impute(data, method = "norm.nob")
  }
  res
}
# Run 100 simulations of the process
res <- simulate(100)
apply(res, c(1, 3), mean, na.rm = TRUE)
```
```{r}
true <- 1
RB <- rowMeans(res[,, "estimate"]) - true
PB <- 100 * abs((rowMeans(res[,, "estimate"]) - true)/ true)
CR <- rowMeans(res[,, "2.5 %"] < true & true < res[,, "97.5 %"])
AW <- rowMeans(res[,, "97.5 %"] - res[,, "2.5 %"])
RMSE <- sqrt(rowMeans((res[,, "estimate"] - true)^2))
data.frame(RB, PB, CR, AW, RMSE)
```



