```{r}
require(mice)
require(lattice)
require(tidyverse)


```

```{r}
# StackExchange example for adding NA values to df.
A <- c(1:10)
B <- c(11:20)
C <- c(21:30)
dff<- data.frame(A,B,C)
# dff <- unlist(dff)
# n <- length(dff) * 0.15
# dff[sample(dff, n)] <- NA
# as.data.frame(matrix(dff, ncol=3))
df <- data.frame(A = 1:10, B = 11:20, c = 21:30)

as.data.frame(lapply(df, function(cc) cc[ sample(c(TRUE, NA), prob = c(0.80, 0.20), size = length(cc), replace = TRUE) ]))
```


```{r}

m = 100
mu = 0
rho = 1
# create normal distn and store as dataframe.
normal_data = rnorm(m, mu, rho)
norm_df <- data.frame(matrix(ncol = 1, nrow = 100))
colnames(norm_df) = "value"
for (i in 1:m){
  norm_df[i,] = normal_data[i]}
# remove ~20% of normally distributed data randomly. Add age variable with no NA values, where age is random value between 0 and 100. Has no missing values. Need at least 2 variables otherwise can't run MI (obviously).
realistic_norm_df <- as.data.frame(lapply(norm_df, function(cc) cc[ sample(c(TRUE, NA), prob = c(0.80, 0.20), size = length(cc), replace = TRUE) ])) %>% 
  add_column(age = floor(runif(100, min=0, max=101))) %>% 
  relocate(age) 
realistic_norm_df

```
# pmm MI [self-made dataset]
```{r}
num_sim = 10
df = realistic_norm_df
df_pmm <- data.frame(matrix(ncol = 6, nrow = 0))
colnames(df_pmm) <- c('intercept', 'slope', 'lambda_intercept', 'lambda_slope', 'fmi_intercept', 'fmi_slope')

imp_pmm <- mice(df, print=F)
complete(imp_pmm)
# plot(imp)

for (i in 1:num_sim){
  # Perform imputation. Without seed = i, I obtain same results for every single iteration of for loop.
  imp_pmm <- mice(df, print=F, seed = i)
  # perform regression analysis
  fit_pmm <- with(imp_pmm, lm(value ~ age))
  pool.fit_pmm <- pool(fit_pmm)
  # Input estimators to df
  intercept <- pool.fit_pmm$pooled[1,3]
  slope <- pool.fit_pmm$pooled[2,3]
  lambda_intercept <- pool.fit_pmm$pooled[1,10]
  lambda_slope <- pool.fit_pmm$pooled[2,10]
  fmi_intercept <- pool.fit_pmm$pooled[1,11]
  fmi_slope <- pool.fit_pmm$pooled[2,11]
  df_pmm[i, ] <- c(intercept, slope, lambda_intercept, lambda_slope, fmi_intercept, fmi_slope)
}
df_pmm
# obtain summary statistics for num_sim simulations.
summary(df_pmm)
```
# norm MI [self-made dataset]
```{r}
num_sim = 10
df = realistic_norm_df
# stores estimators for each of the simulations
df_norm <- data.frame(matrix(ncol = 6, nrow = 0))
colnames(df_norm) <- c('intercept', 'slope', 'lambda_intercept', 'lambda_slope', 'fmi_intercept', 'fmi_slope')

for (i in 1:num_sim){
  # Perform imputation. Without seed = i, I obtain same results for every single iteration of for loop.
  initial <- mice(df, maxit = 0)
  method <- initial$meth
  method["value"] <- "norm"
  imp_norm <- mice(df, meth = method, print=F, seed = i)
  # perform regression analysis
  fit_norm <- with(imp_norm, lm(value ~ age))
  pool.fit_norm <- pool(fit_norm)
  # Input estimators to df
  intercept <- pool.fit_norm$pooled[1,3]
  slope <- pool.fit_norm$pooled[2,3]
  lambda_intercept <- pool.fit_norm$pooled[1,10]
  lambda_slope <- pool.fit_norm$pooled[2,10]
  fmi_intercept <- pool.fit_norm$pooled[1,11]
  fmi_slope <- pool.fit_norm$pooled[2,11]
  df_norm[i, ] <- c(intercept, slope, lambda_intercept, lambda_slope, fmi_intercept, fmi_slope)
}
df_norm
# obtain summary statistics for num_sim simulations.
summary(df_norm)
```




```{r}
# temp, Wind reasonably normal:
hist(airquality$Temp)
# Finding true value of B_1 from complete data model (Q-hat) using complete dataset:

df <- as_tibble(airquality[,3]) %>% 
  add_column(airquality[,4]) %>%
  rename(Wind = value, 
         Temp = "airquality[, 4]") 
fit_complete <- with(df, lm(Temp ~ Wind))
fit_complete$coefficients[2]
```
```{r}
# Add missingness to ~20% of Wind variable observations. 
df_wind_miss <- as.data.frame(lapply(df[1], function(cc) cc[ sample(c(TRUE, NA), prob = c(0.80, 0.20), size = length(cc), replace = TRUE) ])) %>% 
  add_column(airquality[,4]) %>% 
  rename(Temp = "airquality[, 4]")
df_wind_miss  


```
## MI: pmm
```{r}
num_sim = 100
df = df_wind_miss
df_pmm <- data.frame(matrix(ncol = 6, nrow = 0))
colnames(df_pmm) <- c('intercept', 'slope', 'lambda_intercept', 'lambda_slope', 'fmi_intercept', 'fmi_slope')
imp_pmm <- mice(df, print=F)
  # perform regression analysis
  fit_pmm <- with(imp_pmm, lm(Temp ~ Wind))
  summary(fit_pmm)
  pool.fit_pmm <- pool(fi_pmm)
for (i in 1:num_sim){
  # Perform imputation. Without seed = i, I obtain same results for every single iteration of for loop.
  imp_pmm <- mice(df, print=F, seed = i)
  # perform regression analysis
  fit_pmm <- with(imp_pmm, lm(temp ~ wind))
  pool.fit_pmm <- pool(fit_pmm)
  # Input estimators to df
  intercept <- pool.fit_pmm$pooled[1,3]
  slope <- pool.fit_pmm$pooled[2,3]
  lambda_intercept <- pool.fit_pmm$pooled[1,10]
  lambda_slope <- pool.fit_pmm$pooled[2,10]
  fmi_intercept <- pool.fit_pmm$pooled[1,11]
  fmi_slope <- pool.fit_pmm$pooled[2,11]
  df_pmm[i, ] <- c(intercept, slope, lambda_intercept, lambda_slope, fmi_intercept, fmi_slope)
}
df_pmm
# obtain summary statistics for num_sim simulations.
summary(df_pmm)


```

```{r}



```
```{r}
## FAILED ATTEMPT TO APPLY Section 2.5's code to my situation (doesn't even run for me anyway..)
# test.impute <- function(data, m = 5, method = "norm", ...) {
#   imp <- mice(data, method = method, m = m, print = FALSE, ...)
#   fit <- with(imp, lm(Temp ~ Wind))
#   tab <- summary(pool(fit), "all", conf.int = TRUE)
#   as.numeric(tab["x", c("estimate", "2.5 %", "97.5 %")])
# }
# test.impute(df_wind_miss, method = "norm", m = 2)
# runs = 10
# res <- array(NA, dim = c(2, runs, 3))
# imp <- mice(df_wind_miss, method = "norm", m = 2)
# fit <- with(imp, lm(Temp ~ Wind))
# tab <- summary(pool(fit), "all", conf.int = TRUE)
# as.numeric(tab["Wind", c("estimate", "2.5 %", "97.5 %")])
# apply(res, c(1, 3), mean, na.rm = TRUE)
# 
# create.data <- function(beta = 1, sigma2 = 1, n = 50,
#                         run = 1) {
#   set.seed(seed = run)
#   x <- rnorm(n)
#   y <- beta * x + rnorm(n, sd = sqrt(sigma2))
#   cbind(x = x, y = y)
# }
# make.missing <- function(data, p = 0.5){
#   rx <- rbinom(nrow(data), 1, p)
#   data[rx == 0, "x"] <- NA
#   data
# }
# make.missing(df)
# 
# simulate <- function(runs = 10) {
#   res <- array(NA, dim = c(2, runs, 3))
#   dimnames(res) <- list(c("pmm", "norm"),
#                         as.character(1:runs),
#                         c("estimate", "2.5 %","97.5 %"))
#   for(run in 1:runs) {
#     
#     res[1, run, ] <- test.impute(df_wind_miss, method = "pmm",
#                                  m = 2)
#     res[2, run, ] <- test.impute(df_wind_miss, method = "norm")
#   }
#   res
# }
# res <- simulate()
# 
# apply(res, c(1, 3), mean, na.rm = TRUE)
# true <- 1
# RB <- rowMeans(res[,, "estimate"]) - true
# PB <- 100 * abs((rowMeans(res[,, "estimate"]) - true)/ true)
# CR <- rowMeans(res[,, "2.5 %"] < true & true < res[,, "97.5 %"])
# AW <- rowMeans(res[,, "97.5 %"] - res[,, "2.5 %"])
# RMSE <- sqrt(rowMeans((res[,, "estimate"] - true)^2))
# data.frame(RB, PB, CR, AW, RMSE)
```

