---
title: "ROP_Simulations"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
require(mice)
require(lattice)

```
## [INCOMPLETE] ATTEMPT TO CREATE GENERALIZED FUNCTIONS FOR the rf & pmm simulation.
```{r}
# Note: haven't tested what happens for categorical variables [they don't use pmm as default]
 mi_with_method <- function(df, method){
   if (method == "pmm"){
     mice(df, method)}
   else {
     # initialize
     initial <- mice(df, maxit = 0)
     initial_method <- initial$meth
     mice(df, )}
}
```
# pmm MI
```{r}
num_sim = 10
df = nhanes
df_pmm <- data.frame(matrix(ncol = 6, nrow = 0))
colnames(df_pmm) <- c('intercept', 'slope', 'lambda_intercept', 'lambda_slope', 'fmi_intercept', 'fmi_slope')

for (i in 1:num_sim){
  # Perform imputation. Without seed = i, I obtain same results for every single iteration of for loop.
  imp_pmm <- mice(df, print=F, seed = i)
  # perform regression analysis
  fit_pmm <- with(imp_pmm, lm(bmi ~ chl))
  pool.fit_pmm <- pool(fit_pmm)
  # Input estimators to df
  intercept <- pool.fit_pmm$pooled[1,3]
  slope <- pool.fit_pmm$pooled[2,3]
  lambda_intercept <- pool.fit_pmm$pooled[1,10]
  lambda_slope <- pool.fit_pmm$pooled[2,10]
  fmi_intercept <- pool.fit_pmm$pooled[1,11]
  fmi_slope <- pool.fit_pmm$pooled[2,11]
  df_pmm[i, ] <- c(intercept, slope, lambda_intercept, lambda_slope, fmi_intercept, fmi_slope)
}
df_pmm
# obtain summary statistics for num_sim simulations.
summary(df_pmm)

```



# rf simulation
```{r}
num_sim = 100
df = nhanes
df_rf <- data.frame(matrix(ncol = 6, nrow = 0))

colnames(df_rf) <- c('intercept', 'slope', 'lambda_intercept', 'lambda_slope', 'fmi_intercept', 'fmi_slope')
for (i in 1:num_sim){
  # Perform imputation. Without seed = i, I obtain same results for every single iteration of for loop.
  initial <- mice(df, maxit = 0)
  method <- initial$meth
  method["bmi"] <- "rf"
  method["hyp"] <- "rf"
  method["chl"] <- "rf"
  imp_rf <- mice(df, meth = method, print=F, seed = i)
  # perform regression analysis. [Choice of vars ~ Vignette2]
  fit_rf <- with(imp_rf, lm(bmi ~ chl))
  pool.fit_rf <- pool(fit_rf)
  # Input estimators to df
  intercept <- pool.fit_rf$pooled[1,3]
  slope <- pool.fit_rf$pooled[2,3]
  lambda_intercept <- pool.fit_rf$pooled[1,10]
  lambda_slope <- pool.fit_rf$pooled[2,10]
  fmi_intercept <- pool.fit_rf$pooled[1,11]
  fmi_slope <- pool.fit_rf$pooled[2,11]
  df_rf[i, ] <- c(intercept, slope, lambda_intercept, lambda_slope, fmi_intercept, fmi_slope)
}
df_rf
# obtain summary statistics for num_sim simulations.
summary(df_rf)
```
## MAR (Dependence on categorical variable)
```{r}
# Creates function that create a dataset with 50 observations for a linear regression model with a categorical variable.  
create.data <- function(beta = 1, sigma2 = 1, n = 50,
                        run = 1, categorical_var = "gender" , category_one = "M", category_zero = "F") {
  set.seed(seed = run)
  x <- rnorm(n)
  y <- beta * x + rnorm(n, sd = sqrt(sigma2))
  # p represents probability of being in some group (E.g. Male = 1 vs Female = 0)
  z <- rbinom(n, 1, p = 0.5)
  z[z == 0] <- category_zero
  z[z == 1] <- category_one
  
  cbind(x = x, y = y, categorical_var = z)
  # sort df by categorical variable.
  df <- as.data.frame(cbind(x = x, y = y, categorical_var = z)) %>% arrange(categorical_var)
}
# Creates function that removes p_0 % of data from category zero, p_1 % of data from category_one. Note this is effectively MCAR within each group (definition of MAR).
make.missing <- function(data, p_0 = 0.1, p_1 = 0.8 ){
  # don't generate nrow(data) times, generate count of category times.
  counts <- count(data, categorical_var)
  num_cat_zero <-counts[1,2]
  num_cat_one <- counts[2,2]
  r_zero <- rbinom(counts[1,2], 1, p_0)
  r_one <- rbinom(counts[2,2], 1, p_1)
  data[1:num_cat_zero,1][r_zero == 1] <- "dog"
  data[(num_cat_zero +1):nrow(data), 1][r_one ==1] <- "cat"
  data
}
# Function that calls mice (applying imputation) and applies Rubin's Rules, and creates 95% confidence intervals for parameter
test.impute <- function(data, m = 5, method = "norm", ...) {
  imp <- mice(data, method = method, m = m, print = FALSE, ...)
  fit <- with(imp, lm(y ~ x))
  tab <- summary(pool(fit), "all", conf.int = TRUE)
  as.numeric(tab[2, c("estimate", "2.5 %", "97.5 %")])
}
```


```{r}

```

```{r}
typeof(data[1,1])

typeof(data_num_complete[1,1])
```

