---
title: "ROP_Simulations"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
require(mice)
require(lattice)

```
## [INCOMPLETE] ATTEMPT TO CREATE GENERALIZED FUNCTIONS FOR the rf & pmm simulation.
```{r}
# Note: haven't tested what happens for categorical variables [they don't use pmm as default]
 mi_with_method <- function(df, method){
   if (method == "pmm"){
     mice(df, method)}
   else {
     # initialize
     initial <- mice(df, maxit = 0)
     initial_method <- initial$meth
     mice(df, )}
}
```

```{r}
num_sim = 10
df = nhanes
df_pmm <- data.frame(matrix(ncol = 6, nrow = 0))
colnames(df_pmm) <- c('intercept', 'slope', 'lambda_intercept', 'lambda_slope', 'fmi_intercept', 'fmi_slope')

for (i in 1:num_sim){
  # Perform imputation. Without seed = i, I obtain same results for every single iteration of for loop.
  imp_pmm <- mice(df, print=F, seed = i)
  # perform regression analysis
  fit_pmm <- with(imp_pmm, lm(bmi ~ chl))
  pool.fit_pmm <- pool(fit_pmm)
  # Input estimators to df
  intercept <- pool.fit_pmm$pooled[1,3]
  slope <- pool.fit_pmm$pooled[2,3]
  lambda_intercept <- pool.fit_pmm$pooled[1,10]
  lambda_slope <- pool.fit_pmm$pooled[2,10]
  fmi_intercept <- pool.fit_pmm$pooled[1,11]
  fmi_slope <- pool.fit_pmm$pooled[2,11]
  df_pmm[i, ] <- c(intercept, slope, lambda_intercept, lambda_slope, fmi_intercept, fmi_slope)
}
df_pmm
# obtain summary statistics for num_sim simulations.
summary(df_pmm)

```



# rf simulation
```{r}
num_sim = 10
df = nhanes
df_rf <- data.frame(matrix(ncol = 6, nrow = 0))

colnames(df_rf) <- c('intercept', 'slope', 'lambda_intercept', 'lambda_slope', 'fmi_intercept', 'fmi_slope')
for (i in 1:num_sim){
  # Perform imputation. Without seed = i, I obtain same results for every single iteration of for loop.
  initial <- mice(df, maxit = 0)
  method <- initial$meth
  method["bmi"] <- "rf"
  method["hyp"] <- "rf"
  method["chl"] <- "rf"
  imp_rf <- mice(df, meth = method, print=F, seed = i)
  # perform regression analysis. [Choice of vars ~ Vignette2]
  fit_rf <- with(imp_rf, lm(bmi ~ chl))
  pool.fit_rf <- pool(fit_rf)
  # Input estimators to df
  intercept <- pool.fit_rf$pooled[1,3]
  slope <- pool.fit_rf$pooled[2,3]
  lambda_intercept <- pool.fit_rf$pooled[1,10]
  lambda_slope <- pool.fit_rf$pooled[2,10]
  fmi_intercept <- pool.fit_rf$pooled[1,11]
  fmi_slope <- pool.fit_rf$pooled[2,11]
  df_rf[i, ] <- c(intercept, slope, lambda_intercept, lambda_slope, fmi_intercept, fmi_slope)
}
df_rf
# obtain summary statistics for num_sim simulations.
summary(df_rf)
```

